test values: ./runTests.py -nf --ndim 3
{'ndim': 3, 'x': None, 'seed': None, 'flat': (True, True, True), 'new': True}
.........................FF.F.......F.........F.......F........F...................F..FF..................F......F.
======================================================================
FAIL: testIntPowers (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 326, in testIntPowers
    self.assertTrue( self.A.transform(N)== self.A.transform()**N )
AssertionError

======================================================================
FAIL: testMorePowers (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 332, in testMorePowers
    self.assertTrue( self.A**self.K1*self.A**self.K2 == self.A**(self.K1+self.K2))
AssertionError

======================================================================
FAIL: testRealPow (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 365, in testRealPow
    self.assertTrue( self.A/self.A**-1 == self.A**2 )
AssertionError

======================================================================
FAIL: testParadoxes (unitTests.inversionTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 535, in testParadoxes
    self.assertTrue( (self.A&self.B) & ~self.B == self.A & (self.B&~self.B) )
AssertionError

======================================================================
FAIL: testGivenVector (unitTests.givenTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 433, in testGivenVector
    self.assertTrue( mvar.givenVector(self.A,index=0,value=1)==self.A.given(index=0,value=1) )
AssertionError

======================================================================
FAIL: testAnd (unitTests.chainTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 496, in testAnd
    self.assertTrue(measured[:self.ndim] == self.A&self.B)
AssertionError

======================================================================
FAIL: Doctest: __init__.Mvar.KLdiv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.KLdiv
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1971, in KLdiv

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1983, in __init__.Mvar.KLdiv
Failed example:
    assert Matrix(A.KLdiv(A)) == 0 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[2]>", line 1, in <module>
        assert Matrix(A.KLdiv(A)) == 0
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1993, in __init__.Mvar.KLdiv
Failed example:
    assert A.entropy(B) - B.entropy() == A.KLdiv(B)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[6]>", line 1, in <module>
        assert A.entropy(B) - B.entropy() == A.KLdiv(B)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1996, in __init__.Mvar.KLdiv
Failed example:
    assert Matrix(A.entropy(b) - Mvar.fromData(b).entropy()) == A.KLdiv(b)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[8]>", line 1, in <module>
        assert Matrix(A.entropy(b) - Mvar.fromData(b).entropy()) == A.KLdiv(b)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 2007, in __init__.Mvar.KLdiv
Failed example:
    assert KL.dist2() < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[14]>", line 1, in <module>
        assert KL.dist2() < (Z**2)
      File "<string>", line 2, in dist2
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 914, in dist2
        scaled=numpy.array(numpy.inner(deltas,(self**-1).scaled))
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1465, in __pow__
        square=False,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 353, in __init__
        ),'real numbers only'
    AssertionError: real numbers only
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 2013, in __init__.Mvar.KLdiv
Failed example:
    assert KL.dist2() < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[18]>", line 1, in <module>
        assert KL.dist2() < (Z**2)
      File "<string>", line 2, in dist2
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 914, in dist2
        scaled=numpy.array(numpy.inner(deltas,(self**-1).scaled))
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1465, in __pow__
        square=False,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 353, in __init__
        ),'real numbers only'
    AssertionError: real numbers only
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 2020, in __init__.Mvar.KLdiv
Failed example:
    assert KL.dist2() < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[24]>", line 1, in <module>
        assert KL.dist2() < (Z**2)
      File "<string>", line 2, in dist2
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 914, in dist2
        scaled=numpy.array(numpy.inner(deltas,(self**-1).scaled))
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1465, in __pow__
        square=False,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 353, in __init__
        ),'real numbers only'
    AssertionError: real numbers only


======================================================================
FAIL: Doctest: __init__.Mvar.density
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.density
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1872, in density

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1881, in __init__.Mvar.density
Failed example:
    assert Matrix(A.density(data)) == numpy.exp(-A.entropy(data))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.density[1]>", line 1, in <module>
        assert Matrix(A.density(data)) == numpy.exp(-A.entropy(data))
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.dist2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.dist2
  File "/home/olpc/personal-projects/mvar/__init__.py", line 28, in dist2

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 44, in __init__.Mvar.dist2
Failed example:
    assert Matrix(D1)==D2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.dist2[8]>", line 1, in <module>
        assert Matrix(D1)==D2
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 54, in __init__.Mvar.dist2
Failed example:
    assert deltas.dist2() < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.dist2[14]>", line 1, in <module>
        assert deltas.dist2() < (Z**2)
      File "<string>", line 2, in dist2
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 914, in dist2
        scaled=numpy.array(numpy.inner(deltas,(self**-1).scaled))
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1465, in __pow__
        square=False,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 353, in __init__
        ),'real numbers only'
    AssertionError: real numbers only


======================================================================
FAIL: Doctest: __init__.Mvar.entropy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.entropy
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1886, in entropy

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1901, in __init__.Mvar.entropy
Failed example:
    assert Matrix(numpy.log(1/A.density(Sa))) == A.entropy(Sa)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[3]>", line 1, in <module>
        assert Matrix(numpy.log(1/A.density(Sa))) == A.entropy(Sa)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1904, in __init__.Mvar.entropy
Failed example:
    assert Matrix(1/A.density(Sb)) == numpy.exp(A.entropy(Sb)) 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[5]>", line 1, in <module>
        assert Matrix(1/A.density(Sb)) == numpy.exp(A.entropy(Sb))
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1910, in __init__.Mvar.entropy
Failed example:
    assert Matrix(A.entropy()) == A.entropy(A.copy())
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[7]>", line 1, in <module>
        assert Matrix(A.entropy()) == A.entropy(A.copy())
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1939, in __init__.Mvar.entropy
Failed example:
    assert deltas.dist2() < (Z**2)     
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[18]>", line 1, in <module>
        assert deltas.dist2() < (Z**2)
      File "<string>", line 2, in dist2
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 914, in dist2
        scaled=numpy.array(numpy.inner(deltas,(self**-1).scaled))
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1465, in __pow__
        square=False,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 353, in __init__
        ),'real numbers only'
    AssertionError: real numbers only
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1944, in __init__.Mvar.entropy
Failed example:
    assert deltas.dist2() < (Z**2)  
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[22]>", line 1, in <module>
        assert deltas.dist2() < (Z**2)
      File "<string>", line 2, in dist2
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 914, in dist2
        scaled=numpy.array(numpy.inner(deltas,(self**-1).scaled))
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1465, in __pow__
        square=False,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 353, in __init__
        ),'real numbers only'
    AssertionError: real numbers only


======================================================================
FAIL: Doctest: __init__.Mvar.transform
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.transform
  File "/home/olpc/personal-projects/mvar/__init__.py", line 607, in transform

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 617, in __init__.Mvar.transform
Failed example:
    assert A.transform(N)== A.transform()**N  
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.transform[6]>", line 1, in <module>
        assert A.transform(N)== A.transform()**N
    AssertionError


======================================================================
FAIL: Doctest: __init__.givenVector
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.givenVector
  File "/home/olpc/personal-projects/mvar/__init__.py", line 2169, in givenVector

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 2174, in __init__.givenVector
Failed example:
    assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.givenVector[0]>", line 1, in <module>
        assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
    AssertionError


----------------------------------------------------------------------
Ran 115 tests in 37.417s

FAILED (failures=12)
